<a href="https://colab.research.google.com/github/nadunchanna98/machine-learning/blob/main/Sliding_Window_Standardizing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# Sliding Window

In [ ]:
a=np.array([2,3,8,7,5])
a

array([2, 3, 8, 7, 5])

In [ ]:
np.roll(a,1)

array([5, 2, 3, 8, 7])

In [ ]:
np.roll(a,-3)

array([7, 5, 2, 3, 8])

In [ ]:
data = pd.DataFrame({"Date":["2021-01-01","2021-01-02","2021-01-03","2021-01-04","2021-01-05","2021-01-06","2021-01-07"],"Price":[100,200,150,250,280,300,170]})
data


Date  Price
0  2021-01-01    100
1  2021-01-02    200
2  2021-01-03    150
3  2021-01-04    250
4  2021-01-05    280
5  2021-01-06    300
6  2021-01-07    170

In [ ]:
data["Price"].values


array([100, 200, 150, 250, 280, 300, 170], dtype=int64)

In [ ]:
new_data=np.roll(data["Price"].values,-1)
new_data

array([200, 150, 250, 280, 300, 170, 100], dtype=int64)

In [ ]:
data["Next Day Price"]=new_data
data

Date  Price  Next Day Price
0  2021-01-01    100             200
1  2021-01-02    200             150
2  2021-01-03    150             250
3  2021-01-04    250             280
4  2021-01-05    280             300
5  2021-01-06    300             170
6  2021-01-07    170             100

In [ ]:
data.drop("Date",axis=1,inplace=True)
data.drop(6,inplace=True) #after sliding row 6 is not meaning full
data

Price  Next Day Price
0    100             200
1    200             150
2    150             250
3    250             280
4    280             300
5    300             170

# Standardizing

In [ ]:
data=pd.DataFrame({"Height":[1.24,1.34,1.45,0.67,1.66],"width":[56,45,67,78,45]})
data

Height  width
0    1.24     56
1    1.34     45
2    1.45     67
3    0.67     78
4    1.66     45

In [ ]:
np.array((data["Height"]-data["Height"].mean())/data["Height"].std())

array([-0.08627562,  0.1833357 ,  0.47990816, -1.62306018,  1.04609194])

In [ ]:
st_data=data.apply(lambda x:(np.array(x)-np.array(x).mean())/np.array(x).std())
st_data


Height     width
0 -0.096459 -0.171499
1  0.204976 -1.028992
2  0.536554  0.685994
3 -1.814636  1.543487
4  1.169566 -1.028992

In [ ]:
#standerdizing from sklearn module
from sklearn.preprocessing import StandardScaler

In [ ]:
ssc = StandardScaler()

In [ ]:
ssc.fit_transform(data)

array([[-0.09645908, -0.17149859],
       [ 0.20497555, -1.02899151],
       [ 0.53655363,  0.68599434],
       [-1.81463645,  1.54348727],
       [ 1.16956635, -1.02899151]])

In [ ]:
pd.DataFrame(ssc.fit_transform(data),columns=["Height","Width"])

Height     Width
0 -0.096459 -0.171499
1  0.204976 -1.028992
2  0.536554  0.685994
3 -1.814636  1.543487
4  1.169566 -1.028992